### ISSUE TITLE
Gerbers and/or Kicad project in github?

### ISSUE THREAD

**Issue by mwedmark** [gtoal/pitrex#8]
Are there any gerbers public of these Dev boards? Wouldn't it be a good idea to spread them around? I just love making my own and also to be able to extend the community. Also be able to perform pull request for the hardware project would be nice.

**Comment by gtoal** [comment]
Yes, and people have successfully made boards from them.  The files are somewhere on Kevin's wiki - maybe start looking at https://www.ombertech.com/cnk/pitrex/PCB/R1/ - sorry, I don't remember the exact address.

**Comment by mwedmark** [comment]
Thanks alot! That was exactly what I was looking for. Is there a reason for not having them versioned within github? I mean, using v0.1 versions if the general though is that they shouldn't be massproduced yet and with disclaimer.

**Comment by gtoal** [comment]
I hope that's the 1.0 version as currently supplied!  I'ld be quite happy to see it moved to github.  And get open source certification.  I think Kevin just put it on his wiki for convenience.  We're neither of us experienced with github much.  I'll ask him if he can upload the files some time and document them a bit.  I did notice a guy called Lee Ashmore had built a few and you can see his on his Youtube video (near the end): https://www.youtube.com/watch?v=ilNx-vE0big

**Comment by mwedmark** [comment]
Thanks for sharing info! As it seems opening these in Kicad 6.0 (as is my currently installed environment) the Schematics and PCB-files are not in sync totally. My suggesions (as a git user for some years) is to have the PCB project in a separate repo to be able to create tags/revisions seperate from the software. With some additional info I could help you with this, but of course, the original files need to be in sync. Currently it is trying to do some auto mapping against the new Kicad Libraries.

**Comment by gtoal** [comment]
Since I'm not the hardware guy, it might be quicker if you join our mailing list at https://groups.io/g/pitrex-dev and talk to Kevin directly...

**Comment by mwedmark** [comment]
Thanks!
